sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tweidner103/shirts -f Dockerfile.dev .

script:
  - docker run -e CI=true tweidner103/shirts npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "shirts"
  env: "Shirts-env"
  # s3 bucket name
  bucket_name: "elasticbeanstalk-us-west-1-741024833687"
  bucket_path: "shirts"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
